# -*- mode: ruby -*-
# vi: set ft=ruby :

login = "vkaron"

server_name = "#{login}S"
server_ip   = "192.168.42.110"
worker_name = "#{login}SW"
worker_ip   = "192.168.42.111"

file_path = "file:///goinfre/vkaron/"
url_path = "https://cloud.centos.org/centos/9-stream/x86_64/images/"
image_name = "CentOS-Stream-Vagrant-9-20211115.2.x86_64.vagrant-virtualbox.box"

Vagrant.configure("2") do |config|

  config.vm.box     = "centos8"
  unless File.exist? "#{file_path}#{image_name}"
    config.vm.box_url = "#{url_path}#{image_name}"
  else
    config.vm.box_url = "#{file_path}#{image_name}"
  end
  config.vm.box_check_update = false
  config.vm.synced_folder ".", "/vagrant", disabled: true

  config.vm.provider :virtualbox do |v|
    v.customize ["modifyvm", :id, "--memory", 1024]
    v.customize ["modifyvm", :id, "--cpus", 1]
    v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    v.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
  end

  # Server
  config.vm.define server_name do |control|
    control.vm.hostname = server_name
    control.vm.network "private_network", ip: server_ip
    control.vm.provider "virtualbox" do |v|
      v.customize ["modifyvm", :id, "--name", server_name]
    end
    control.vm.provision "shell", privileged: false, path: "scripts/server_script.sh", env: {"NODE_IP": server_ip}
  end

  # ServerWorker
  config.vm.define worker_name do |control|
    control.vm.hostname = worker_name
    control.vm.network "private_network", ip: worker_ip
    control.vm.provider "virtualbox" do |v|
      v.customize ["modifyvm", :id, "--name", worker_name]
    end
    control.vm.provision "file", source: ".vagrant/machines/#{server_name}/virtualbox/private_key", destination: "~/private_key"
    control.vm.provision "shell", privileged: false, path: "scripts/worker_script.sh", env: {"SERVER_IP": server_ip, "NODE_IP": worker_ip}
  end

end